### ISSUE TITLE
Server-side storage

### ISSUE THREAD

**Issue by exteon** [behigh/redmine_timelog_timer#11]
It would be nice if there were a server-side storage for timers' start times. It would provide the following features:
- List of what users are working on at the moment; this would be an extremely nice feature to have
- Possibility to stop a timer on a different computer/browser/timezone than where it's started. We have a workflow where developers change locations during a day, and they most often than not forget to log the time before logging off a station.
- No more need for client-side session storage, on every init the client JS will get the "time elapsed so far" data from the server and start incrementing for visualization purposes only, as the actual delta is always computed on the server

**Comment by behigh** [comment]
This plugin is designed as a client-side and will not be updated to the server-side. To do this, there are alternatives.
